### ISSUE TITLE
Hera's gas accounting in callSenderBalanceExceeds128Bits

### ISSUE THREAD

**Issue by gballet** [ewasm/hera#456]
The `callSenderBalanceExceeds128Bits` test poses some problem with wagon and as a DDoS attack vector.

The initial state is as such:
```yaml
  pre:
    a94f5374fce5edbc8e2a8697c15331677e6ebf0b:
      balance: 100000000000
      code: ''
      nonce: '0x4'
      storage: {}
    deadbeef00000000000000000000000000000001:
      balance: 100000000000
      code: ''
      nonce: ''
      storage: {}
    deadbeef00000000000000000000000000000000:
      balance: 340282366920938463463374607431768211600
      nonce: ''
      storage: {}
```

and the expected output is:

```wast
  expect:
    - indexes:
        data: !!int -1
        gas: !!int -1
        value: !!int -1
      network:
        - ALL
      result:
        # Balances remain the same as because of:
        # InternalError: Account balance (or transaction value) exceeds 128 bits
        a94f5374fce5edbc8e2a8697c15331677e6ebf0b:
          balance: 100000000000
        deadbeef00000000000000000000000000000000:
          balance: 340282366920938463463374607431768211600
          storage: {
            # Nothing should be store due to InternalError
            1: "0"
          }
        deadbeef00000000000000000000000000000001:
          balance: 100000000000
          storage: {}
```

This happens because upon [checking the sender's account balance for the value transfer](https://github.com/ewasm/hera/blob/v0.2.0/src/eei.cpp#L496), Hera also checks that [the account balance itself is lower than 128 bits](https://github.com/ewasm/hera/blob/v0.2.0/src/eei.cpp#L808) and if it is more, it will interrupt the program execution and not charge the sender's account anything.

I propose that this behavior be changed, at least to charge the transaction gas (21000), for the following reasons:

  * Because the wagon implementation relies on a lot of the original geth code, not charging the transaction gas cost would require a significant rewrite.
  * In the unlikely event that someone has a balance of more than 340282366920938463463374607431768211456, well, good for them. Why should we care?
  * In that case, this person could craft a huge number of transactions and DDoS the network without even being charged for it.

So I suggest to replace the 128 bit account balance check with a 256 bit one.
